### ISSUE TITLE
html works+ css+>>>

### ISSUE THREAD

**Issue by RiyaDhami13** [html/weblocks-jquery#9]
i am doing html projects here

**Comment by hazrate-coder** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 1st form </title>
</head>

<body style="background-color: cornsilk;">
    <form>
        <h2>application form</h2>

        <label for="name">enter your name:</label>
        <input type="text" id="name" style="background-color: skyblue;"> <br><br>

        <label for="email">enter your email:</label>
        <input type="email" id="email" style="background-color: skyblue;"><br><br>

        <label for="phone">enter tour number :</label>
        <input type="tel" name="phone" id="phone" style="background-color: skyblue;"><br><br>

        <label for="chosefile">resume</label>
        <input type="file" id="chosefile" style="background-color:skyblue;"><br><br>

        <label for="experience">experience</label>
        <input type="number" id="experience" min="0" max="30" style="background-color: skyblue;"><br><br>

        <label for="casteselact">selact caste:</label>
        <select name="casteselact" id="casteselact">
            <option value="obc">obs</option>
            <option value="sc">sc</option>
            <option value="st">st</option>
            <option value="gendral">gendral</option>

        </select> <br><br>
        <fieldset style="background-color: skyblue;">
            <legend>select the coeces</legend>
            <label for="box1">HTML</label>
            <input type="checkbox" id="box1">
            <label for="box2">CSS</label>
            <input type="checkbox" id="box2">
            <label for="box3">jawa</label>
            <input type="checkbox" id="box3">

        </fieldset><br>
        <label for="comments">comments</label><br>
        <textarea id="comments" cols="30" rows="10" style="background-color: skyblue;">
        </textarea>
        <button>registerd</button>

    </form><br>
    <br>
    <br>
    <hr>
    <hr>
    <fieldset style="background-color:wheat">
        <div>
            <div>
                <h2> MOHAMMAD MOHSIN ANSARI </h2>
                <P>CONTACT no: <a href="tel:9584350051">9584350051</a> </P>
                <p>instagram: <a href="https://www.instagram.com/">Danger_._m</a> </p>
                <p>github: <a href="https://github.com/join/recommended_plan">Hazrate-coder</a></p>
            </div>
            <table>
                <tr>
                    <td> <img src="" width="125" height="125"> </td>
                    <td>Mohsin is a Muslim Boy Name. Mohsin name meaning is Helpful, Who Gives Benefits To Others. It
                        has multiple Islamic meaning. The name is originated from Arabic. The lucky number of Mohsin
                        name is 5.Mohsin is a Muslim Boy Name. Mohsin name meaning is Helpful, Who Gives Benefits To
                        Others. It has multiple Islamic meaning. The name is originated from Arabic. The lucky number of
                        Mohsin name is 5.Mohsin is a Muslim Boy Name. Mohsin name meaning is Helpful, Who Gives Benefits
                        To Others. It has multiple Islamic meaning. The name is originated from Arabic. The lucky number
                        of Mohsin name is 5.Mohsin is a Muslim Boy Name. Mohsin name meaning is Helpful, Who Gives
                        Benefits To Others. It has multiple Islamic meaning. The name is originated from Arabic. The
                        lucky number of Mohsin name is 5.Mohsin is a Muslim Boy Name. Mohsin name meaning is Helpful,
                        Who Gives Benefits To Others. It has multiple Islamic meaning. The name is originated from
                        Arabic. The lucky number of Mohsin name is 5.</td>
                </tr>
            </table>

            <h2>Education</h2>
            <ul>
                <li> bachelor of computer application </li>
                <li> masters of computer application </li>
            </ul>
            <h2>work experionce</h2>
            <h3> micrisoft softwere engnering </h3>
            <p> -> softwere engenering department as a counsler</p>
            <p> -> softwere engnering department as a manager</p>

            <details>
                <summary>my full address </summary>
                768nai basti ikta chok gohalpur jabalpur
            </details>
            <Details>
                <summary>all certificket list</summary>
                <ul>
                    <li>bachler of computer application</li>
                    <li>masters of computer application</li>
                    <li>phalana of phalana</li>
                    <li> <a href="cot wali img.jpg">and my image</a></li>
                    <li> <a href="Coolio_-_gangster_paradise_(_slowed_+_reverb_)(128k).mp3">tap and play</a></li>
                </ul>

            </Details>


        </div>
    </fieldset>

</body>

</html>
